#클래스 내에서 사용될 상수값 정의

# 파일 업로드시의 파일 경로
file:
  directory: D:/SGSG/download/mandalart

#페이징의 기본 사이즈
const:
  default-page-size: 20


#어플리케이션 설정
spring:
  application:
    name: mandalartWeb



  config:
    import: "classpath:application-secret.yml"

  #File 업로드 설정
  servlet:
    multipart:
      max-file-size: 50MB

#MyBatis 설정
mybatis:
  mapper-locations: mappers/**/*.xml

#Swagger 설정
springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true
